../build/contains_baseline libcudf_bench/skew_small_16.csv
../build/contains_baseline libcudf_bench/skew_small_32.csv
../build/contains_baseline libcudf_bench/skew_small_64.csv
../build/contains_baseline libcudf_bench/uniform_dist_small_16_128.csv
../build/contains_baseline libcudf_bench/normal_small_16_128.csv
../build/contains_baseline libcudf_bench/bimodal_small_16_5_512_100.csv
../build/contains_baseline libcudf_bench/bimodal_small_32_10_512_100.csv
../build/contains_baseline libcudf_bench/bimodal_small_64_20_512_100.csv
../build/contains_baseline libcudf_bench/bimodal_small_16_5_8192_500.csv
../build/contains_baseline libcudf_bench/bimodal_small_32_10_8192_500.csv
../build/contains_baseline libcudf_bench/bimodal_small_64_20_8192_500.csv
../build/contains_baseline libcudf_bench/bimodal_small_16_5_65536_2000.csv  
../build/contains_baseline libcudf_bench/bimodal_small_32_10_65536_2000.csv
../build/contains_baseline libcudf_bench/bimodal_small_64_20_65536_2000.csv
../build/contains_baseline skew_small_fb_comments.csv
../build/contains_baseline skew_small_fb_posts.csv
../build/contains_baseline skew_small_reddit.csv
../build/contains_baseline skew_small_twitter.csv