export PATH=~/micromamba/envs/cudf_dev/NVIDIA-Nsight-Compute-2026.1:$PATH
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu skew_32.csv het > ../profiles/het/het_skew_32.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu skew_16.csv het > ../profiles/het/het_skew_16.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu skew_64.csv het > ../profiles/het/het_skew_64.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu uniform_dist_16_128.csv het > ../profiles/het/het_uniform.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu normal_16_128.csv het > ../profiles/het/het_normal.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_16_5_512_100.csv het > ../profiles/het/het_bimodal_16_5_512_100.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_32_10_512_100.csv het > ../profiles/het/het_bimodal_32_10_512_100.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_64_20_512_100.csv het > ../profiles/het/het_bimodal_64_20_512_100.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_16_5_8192_500.csv het > ../profiles/het/het_bimodal_16_5_8192_500.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_32_10_8192_500.csv het > ../profiles/het/het_bimodal_32_10_8192_500.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_64_20_8192_500.csv het > ../profiles/het/het_bimodal_64_20_8192_500.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_16_5_65536_2000.csv het > ../profiles/het/het_bimodal_16_5_65536_2000.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_32_10_65536_2000.csv het > ../profiles/het/het_bimodal_32_10_65536_2000.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_64_20_65536_2000.csv het > ../profiles/het/het_bimodal_64_20_65536_2000.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu fb_comments.csv het > ../profiles/het/het_fb_comments.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu fb_posts.csv het > ../profiles/het/het_fb_posts.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu reddit_utf8.csv het > ../profiles/het/het_reddit.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu twitter_utf8.csv het > ../profiles/het/het_twitter.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu amazon_arts_and_crafts.csv het > ../profiles/het/het_amazon.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu yelp_reviews.csv het > ../profiles/het/het_yelp.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu github_commits.csv het > ../profiles/het/het_github.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu common_crawl_urls.csv het > ../profiles/het/het_urls.txt

ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu skew_32.csv cudf > ../profiles/cudf/cudf_skew_32.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu skew_16.csv cudf > ../profiles/cudf/cudf_skew_16.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu skew_64.csv cudf > ../profiles/cudf/cudf_skew_64.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu uniform_dist_16_128.csv cudf > ../profiles/cudf/cudf_uniform.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu normal_16_128.csv cudf > ../profiles/cudf/cudf_normal.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_16_5_512_100.csv cudf > ../profiles/cudf/cudf_bimodal_16_5_512_100.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_32_10_512_100.csv cudf > ../profiles/cudf/cudf_bimodal_32_10_512_100.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_64_20_512_100.csv cudf > ../profiles/cudf/cudf_bimodal_64_20_512_100.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_16_5_8192_500.csv cudf > ../profiles/cudf/cudf_bimodal_16_5_8192_500.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_32_10_8192_500.csv cudf > ../profiles/cudf/cudf_bimodal_32_10_8192_500.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_64_20_8192_500.csv cudf > ../profiles/cudf/cudf_bimodal_64_20_8192_500.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_16_5_65536_2000.csv cudf > ../profiles/cudf/cudf_bimodal_16_5_65536_2000.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_32_10_65536_2000.csv cudf > ../profiles/cudf/cudf_bimodal_32_10_65536_2000.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_64_20_65536_2000.csv cudf > ../profiles/cudf/cudf_bimodal_64_20_65536_2000.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu fb_comments.csv cudf > ../profiles/cudf/cudf_fb_comments.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu fb_posts.csv cudf > ../profiles/cudf/cudf_fb_posts.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu reddit_utf8.csv cudf > ../profiles/cudf/cudf_reddit.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu twitter_utf8.csv cudf > ../profiles/cudf/cudf_twitter.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu amazon_arts_and_crafts.csv cudf > ../profiles/cudf/cudf_amazon.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu yelp_reviews.csv cudf > ../profiles/cudf/cudf_yelp.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu github_commits.csv cudf > ../profiles/cudf/cudf_github.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu common_crawl_urls.csv cudf > ../profiles/cudf/cudf_urls.txt

ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu skew_32.csv thread > ../profiles/thread/thread_skew_32.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu skew_16.csv thread > ../profiles/thread/thread_skew_16.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu skew_64.csv thread > ../profiles/thread/thread_skew_64.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu uniform_dist_16_128.csv thread > ../profiles/thread/thread_uniform.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu normal_16_128.csv thread > ../profiles/thread/thread_normal.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_16_5_512_100.csv thread > ../profiles/thread/thread_bimodal_16_5_512_100.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_32_10_512_100.csv thread > ../profiles/thread/thread_bimodal_32_10_512_100.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_64_20_512_100.csv thread > ../profiles/thread/thread_bimodal_64_20_512_100.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_16_5_8192_500.csv thread > ../profiles/thread/thread_bimodal_16_5_8192_500.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_32_10_8192_500.csv thread > ../profiles/thread/thread_bimodal_32_10_8192_500.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_64_20_8192_500.csv thread > ../profiles/thread/thread_bimodal_64_20_8192_500.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_16_5_65536_2000.csv thread > ../profiles/thread/thread_bimodal_16_5_65536_2000.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_32_10_65536_2000.csv thread > ../profiles/thread/thread_bimodal_32_10_65536_2000.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_64_20_65536_2000.csv thread > ../profiles/thread/thread_bimodal_64_20_65536_2000.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu fb_comments.csv thread > ../profiles/thread/thread_fb_comments.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu fb_posts.csv thread > ../profiles/thread/thread_fb_posts.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu reddit_utf8.csv thread > ../profiles/thread/thread_reddit.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu twitter_utf8.csv thread > ../profiles/thread/thread_twitter.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu amazon_arts_and_crafts.csv thread > ../profiles/thread/thread_amazon.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu yelp_reviews.csv thread > ../profiles/thread/thread_yelp.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu github_commits.csv thread > ../profiles/thread/thread_github.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu common_crawl_urls.csv thread > ../profiles/thread/thread_urls.txt

ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu skew_32.csv warp > ../profiles/warp/warp_skew_32.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu skew_16.csv warp > ../profiles/warp/warp_skew_16.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu skew_64.csv warp > ../profiles/warp/warp_skew_64.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu uniform_dist_16_128.csv warp > ../profiles/warp/warp_uniform.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu normal_16_128.csv warp > ../profiles/warp/warp_normal.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_16_5_512_100.csv warp > ../profiles/warp/warp_bimodal_16_5_512_100.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_32_10_512_100.csv warp > ../profiles/warp/warp_bimodal_32_10_512_100.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_64_20_512_100.csv warp > ../profiles/warp/warp_bimodal_64_20_512_100.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_16_5_8192_500.csv warp > ../profiles/warp/warp_bimodal_16_5_8192_500.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_32_10_8192_500.csv warp > ../profiles/warp/warp_bimodal_32_10_8192_500.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_64_20_8192_500.csv warp > ../profiles/warp/warp_bimodal_64_20_8192_500.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_16_5_65536_2000.csv warp > ../profiles/warp/warp_bimodal_16_5_65536_2000.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_32_10_65536_2000.csv warp > ../profiles/warp/warp_bimodal_32_10_65536_2000.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_64_20_65536_2000.csv warp > ../profiles/warp/warp_bimodal_64_20_65536_2000.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu fb_comments.csv warp > ../profiles/warp/warp_fb_comments.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu fb_posts.csv warp > ../profiles/warp/warp_fb_posts.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu reddit_utf8.csv warp > ../profiles/warp/warp_reddit.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu twitter_utf8.csv warp > ../profiles/warp/warp_twitter.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu amazon_arts_and_crafts.csv warp > ../profiles/warp/warp_amazon.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu yelp_reviews.csv warp > ../profiles/warp/warp_yelp.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu github_commits.csv warp > ../profiles/warp/warp_github.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu common_crawl_urls.csv warp > ../profiles/warp/warp_urls.txt

ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu skew_32.csv badhet > ../profiles/badhet/badhet_skew_32.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu skew_16.csv badhet > ../profiles/badhet/badhet_skew_16.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu skew_64.csv badhet > ../profiles/badhet/badhet_skew_64.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu uniform_dist_16_128.csv badhet > ../profiles/badhet/badhet_uniform.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu normal_16_128.csv badhet > ../profiles/badhet/badhet_normal.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_16_5_512_100.csv badhet > ../profiles/badhet/badhet_bimodal_16_5_512_100.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_32_10_512_100.csv badhet > ../profiles/badhet/badhet_bimodal_32_10_512_100.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_64_20_512_100.csv badhet > ../profiles/badhet/badhet_bimodal_64_20_512_100.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_16_5_8192_500.csv badhet > ../profiles/badhet/badhet_bimodal_16_5_8192_500.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_32_10_8192_500.csv badhet > ../profiles/badhet/badhet_bimodal_32_10_8192_500.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_64_20_8192_500.csv badhet > ../profiles/badhet/badhet_bimodal_64_20_8192_500.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_16_5_65536_2000.csv badhet > ../profiles/badhet/badhet_bimodal_16_5_65536_2000.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_32_10_65536_2000.csv badhet > ../profiles/badhet/badhet_bimodal_32_10_65536_2000.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu bimodal_64_20_65536_2000.csv badhet > ../profiles/badhet/badhet_bimodal_64_20_65536_2000.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu fb_comments.csv badhet > ../profiles/badhet/badhet_fb_comments.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu fb_posts.csv badhet > ../profiles/badhet/badhet_fb_posts.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu reddit_utf8.csv badhet > ../profiles/badhet/badhet_reddit.csv.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu twitter_utf8.csv badhet > ../profiles/badhet/badhet_twitter.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu amazon_arts_and_crafts.csv badhet > ../profiles/badhet/badhet_amazon.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu yelp_reviews.csv badhet > ../profiles/badhet/badhet_yelp.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu github_commits.csv badhet > ../profiles/badhet/badhet_github.txt
ncu --section SpeedOfLight --kernel-name 'regex:transform_kernel|contains_warp_parallel_fn' ../build/contains_ncu common_crawl_urls.csv badhet > ../profiles/badhet/badhet_urls.txt